version: '3'
networks: 
  dockerlan:
  report:
services:
# Start the mysql container
  mysql:
    container_name: sonar_mysql
    build: ./mysql
    volumes:
     - .:/tmp/report_deposit
    networks:
     - report
    ports:
     - "3306:3306"
# Start the SonarQube container
  sonarqube:
    container_name: sonarqube
    image: "sonarqube:7.1"
    networks:
     - report
     - dockerlan
    ports:
     - "9000:9000"